apiVersion : apps/v1
kind: Deployment
metadata:
  name: phpprojecttest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpprojecttest
  template:
    metadata:
      labels:
        app: phpprojecttest 
    spec:
      containers:
        - name: phpprojecttest 
          image: sharanlabacr.azurecr.io/phpprojecttest
          ports:
          - containerPort: 8080